name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}-docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Cache multiple Pips
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-3.10-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry~=1.2
      - run: poetry config virtualenvs.in-project true
      - run: poetry install --sync
      - run: poetry run mkdocs gh-deploy --force
